apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeter-server-sa
  namespace: workload

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server
  namespace: workload
  labels:
    app: greeter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      namespace: workload
      labels:
        app: greeter-server
#        spire.spiffe.io/spiffeid: greeter-server
    spec:
      serviceAccountName: greeter-server-sa
      containers:
        - name: greeter-server
          image: greeter-server:demo
          imagePullPolicy: Never
#          volumeMounts:
#            - name: spiffe-workload-api
#              mountPath: /spiffe-workload-api
#              readOnly: true
          env:
          - name: LISTEN_ADDR
            value: ":8443"
#          - name: SPIFFE_ENDPOINT_SOCKET
#            value: unix:///spiffe-workload-api/spire-agent.sock
#      volumes:
#      - name: spiffe-workload-api
#        csi:
#          driver: "csi.spiffe.io"
#          readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: greeter-server
  namespace: workload
spec:
    selector:
        app: greeter-server
    ports:
      - name: grpc-api
        port: 8443
        protocol: TCP

---
